/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.kaurel.klang.xtext.ui.contentassist;

import com.kaurel.klang.xtext.ui.contentassist.AbstractKlangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class KlangProposalProvider extends AbstractKlangProposalProvider {
}
