/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.kaurel.klang.xtext.tests;

import com.google.inject.Inject;
import com.kaurel.klang.xtext.tests.KlangInjectorProvider;
import klang.GameDef;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(KlangInjectorProvider.class)
@SuppressWarnings("all")
public class KlangParsingTest {
  @Inject
  private ParseHelper<GameDef> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final GameDef result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
