/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.kaurel.klang.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KlangStandaloneSetup extends KlangStandaloneSetupGenerated {

	def static void doSetup() {
		new KlangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
