<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="klang"
    nsURI="platform:/plugin/com.kaurel.klang.model/model/klang.ecore"
    nsPrefix="klang">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SceneActor"
      eSuperTypes="#//AbstractActor">
    <eOperations
        name="print">
      <eParameters
          name="message"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="program"
        eType="#//Program"
        eOpposite="#//Program/sceneActor"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SpriteActor"
      eSuperTypes="#//AbstractActor">
    <eOperations
        name="print">
      <eParameters
          name="message"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="setColor">
      <eParameters
          name="red"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
      <eParameters
          name="green"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
      <eParameters
          name="blue"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="program"
        eType="#//Program"
        eOpposite="#//Program/spriteActors"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EventHandler"
      abstract="true">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="statements"
        upperBound="-1"
        eType="ecore:EClass klang-expr.ecore#//Statement"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="actor"
        lowerBound="1"
        eType="#//AbstractActor"
        changeable="false"
        eOpposite="#//AbstractActor/eventHandlers"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableDeclaration">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="scope&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="expression"
        eType="ecore:EClass klang-expr.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="actor"
        eType="#//AbstractActor"
        eOpposite="#//AbstractActor/localVariables"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AbstractActor"
      abstract="true">
    <eOperations
        name="isInScope"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="getVariableDeclaration"
        eType="#//VariableDeclaration">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="isInLocalScope"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="isInParentScope"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="random"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="eventHandlers"
        upperBound="-1"
        eType="#//EventHandler"
        containment="true"
        eOpposite="#//EventHandler/actor"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="subject"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="localVariables"
        upperBound="-1"
        eType="#//VariableDeclaration"
        containment="true"
        eOpposite="#//VariableDeclaration/actor"/>
    <eGenericSuperTypes
        eClassifier="#//TreeNode">
      <eTypeArguments
          eClassifier="#//AbstractActor"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="GameStart"
      eSuperTypes="#//EventHandler"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SpriteClicked"
      eSuperTypes="#//EventHandler"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="KeyPressed"
      eSuperTypes="#//EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="key"
        eType="#//Keys"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollidesWith"
      eSuperTypes="#//EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="target"
        eType="#//SpriteActor"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Program">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="sceneActor"
        eType="#//SceneActor"
        containment="true"
        eOpposite="#//SceneActor/program"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="spriteActors"
        upperBound="-1"
        eType="#//SpriteActor"
        containment="true"
        eOpposite="#//SpriteActor/program"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TreeNode"
      abstract="true"
      interface="true">
    <eTypeParameters
        name="T">
      <eBounds
          eClassifier="#//TreeNode">
        <eTypeArguments
            eTypeParameter="#//TreeNode/T"/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="children"
        upperBound="-1"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"
        resolveProxies="false">
      <eGenericType
          eTypeParameter="#//TreeNode/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parent"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"
        resolveProxies="false">
      <eGenericType
          eTypeParameter="#//TreeNode/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TreeTraversal">
    <eOperations
        name="BreadthFirst"
        upperBound="-1">
      <eGenericType
          eTypeParameter="#//TreeTraversal/BreadthFirst/T"/>
      <eTypeParameters
          name="T">
        <eBounds
            eClassifier="#//TreeNode">
          <eTypeArguments
              eTypeParameter="#//TreeTraversal/BreadthFirst/T"/>
        </eBounds>
      </eTypeParameters>
      <eParameters
          name="root">
        <eGenericType
            eTypeParameter="#//TreeTraversal/BreadthFirst/T"/>
      </eParameters>
    </eOperations>
    <eOperations
        name="DepthFirst"
        upperBound="-1">
      <eGenericType
          eTypeParameter="#//TreeTraversal/DepthFirst/T"/>
      <eTypeParameters
          name="T">
        <eBounds
            eClassifier="#//TreeNode">
          <eTypeArguments
              eTypeParameter="#//TreeTraversal/DepthFirst/T"/>
        </eBounds>
      </eTypeParameters>
      <eParameters
          name="root">
        <eGenericType
            eTypeParameter="#//TreeTraversal/DepthFirst/T"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EEnum"
      name="Keys">
    <eLiterals
        name="A"/>
    <eLiterals
        name="B"
        value="1"/>
    <eLiterals
        name="C"
        value="2"/>
    <eLiterals
        name="D"
        value="3"/>
    <eLiterals
        name="E"
        value="4"/>
    <eLiterals
        name="F"
        value="5"/>
    <eLiterals
        name="G"
        value="6"/>
    <eLiterals
        name="H"
        value="7"/>
    <eLiterals
        name="I"
        value="8"/>
    <eLiterals
        name="J"
        value="9"/>
    <eLiterals
        name="K"
        value="10"/>
    <eLiterals
        name="L"
        value="11"/>
    <eLiterals
        name="M"
        value="12"/>
    <eLiterals
        name="N"
        value="13"/>
    <eLiterals
        name="O"
        value="14"/>
    <eLiterals
        name="P"
        value="15"/>
    <eLiterals
        name="Q"
        value="16"/>
    <eLiterals
        name="R"
        value="17"/>
    <eLiterals
        name="S"
        value="18"/>
    <eLiterals
        name="T"
        value="19"/>
    <eLiterals
        name="U"
        value="20"/>
    <eLiterals
        name="V"
        value="21"/>
    <eLiterals
        name="W"
        value="22"/>
    <eLiterals
        name="X"
        value="23"/>
    <eLiterals
        name="Y"
        value="24"/>
    <eLiterals
        name="Z"
        value="25"/>
    <eLiterals
        name="SPACE"
        value="26"/>
    <eLiterals
        name="ENTER"
        value="27"/>
    <eLiterals
        name="UP"
        value="28"/>
    <eLiterals
        name="DOWN"
        value="29"/>
    <eLiterals
        name="LEFT"
        value="30"/>
    <eLiterals
        name="RIGHT"
        value="31"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="MessageReceived"
      eSuperTypes="#//EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
