<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="klang"
    nsURI="http://www.example.org/klang"
    nsPrefix="klang">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SceneActor">
    <eOperations
        name="print">
      <eParameters
          name="message"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eGenericSuperTypes
        eClassifier="#//AbstractActor">
      <eTypeArguments
          eClassifier="#//SpriteActor"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SpriteActor">
    <eOperations
        name="print">
      <eParameters
          name="message"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="getX"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eOperations
        name="getY"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    <eOperations
        name="setY">
      <eParameters
          name="y"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    </eOperations>
    <eOperations
        name="setX">
      <eParameters
          name="x"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    </eOperations>
    <eOperations
        name="print"
        lowerBound="1">
      <eParameters
          name="message"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    </eOperations>
    <eOperations
        name="sleep">
      <eParameters
          name="sleepDuration"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
    </eOperations>
    <eGenericSuperTypes
        eClassifier="#//AbstractActor">
      <eTypeArguments
          eClassifier="#//SpriteActor"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="statements"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="actor"
        lowerBound="1"
        changeable="false"
        eOpposite="#//AbstractActor/eventHandlers">
      <eGenericType
          eClassifier="#//AbstractActor">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="WhileLoop"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="predicate"
        eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="loopBlock"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="If"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="predicate"
        eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ifBlock"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="elseBlock"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ForeverLoop"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="loopStatements"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Yield"
      eSuperTypes="#//Statement"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableDeclaration"
      eSuperTypes="#//AbstractElement">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="scope&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="expression"
        eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableAssignment"
      eSuperTypes="#//Statement">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="scope type&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="expression"
        eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="variableName"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Expression"
      eSuperTypes="#//AbstractElement"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Or"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="And"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Plus"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Minus"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Multiply"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Divide"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LessThan"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Equal"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="GreaterThan"
      eSuperTypes="#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="left"
        eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="right"
        eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Not"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BooleanLiteral"
      eSuperTypes="#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DoubleLiteral"
      eSuperTypes="#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StringLiteral"
      eSuperTypes="#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableReference"
      eSuperTypes="#//Expression">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="scope&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="variableName"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UnaryOperator"
      eSuperTypes="#//Expression">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="type&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="expression"
        eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BinaryOperator"
      eSuperTypes="#//Expression">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="type&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="left"
        eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="right"
        eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="FunctionCall"
      eSuperTypes="#//Expression #//Statement">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="methodDeclaration&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parameters"
        upperBound="-1"
        eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Statement"
      abstract="true"
      interface="true"
      eSuperTypes="#//AbstractElement"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AbstractElement"
      abstract="true">
    <eOperations
        name="getActor">
      <eGenericType
          eClassifier="#//AbstractActor">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="GameStart"
      eSuperTypes="#//EventHandler"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SpriteClicked"
      eSuperTypes="#//EventHandler"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="KeyPressed"
      eSuperTypes="#//EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="key"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollidesWith"
      eSuperTypes="#//EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="target"
        eType="#//SpriteActor"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="IntegerLiteral"
      eSuperTypes="#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Sleep"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="duration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UnaryMinus"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ToDouble"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ToInt"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AbstractActor"
      abstract="true">
    <eTypeParameters
        name="A">
      <eBounds
          eClassifier="#//AbstractActor">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eOperations
        name="getSubtree"
        upperBound="-1">
      <eGenericType
          eClassifier="#//AbstractActor">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="eventHandlers"
        upperBound="-1"
        eType="#//EventHandler"
        containment="true"
        eOpposite="#//EventHandler/actor"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="subject"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        transient="true"/>
    <eGenericSuperTypes
        eClassifier="#//Scope">
      <eTypeArguments
          eTypeParameter="#//AbstractActor/A"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Scope">
    <eTypeParameters
        name="S">
      <eBounds
          eClassifier="#//Scope">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eOperations
        name="isInScope"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="getVariableDeclaration"
        eType="#//VariableDeclaration">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="isInLocalScope"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations
        name="isInParentScope"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters
          name="variableName"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="localVariables"
        upperBound="-1"
        eType="#//VariableDeclaration"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="children"
        upperBound="-1"
        containment="true"
        eOpposite="#//Scope/parent">
      <eGenericType
          eTypeParameter="#//Scope/S"/>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parent"
        changeable="false"
        eOpposite="#//Scope/children">
      <eGenericType
          eClassifier="#//Scope">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
