<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="klang"
    nsURI="http://www.example.org/klang"
    nsPrefix="klang">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SceneActor"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Actor">
    <eOperations
        name="print">
      <eParameters
          name="message"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="program"
        eType="#//Program"
        eOpposite="#//Program/sceneActor"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SpriteActor"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Actor">
    <eOperations
        name="print">
      <eParameters
          name="message"
          lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="program"
        eType="#//Program"
        eOpposite="#//Program/spriteActors"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="WhileLoop"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="predicate"
        eType="ecore:EClass ../../com.kaurel.klang.core/model/core.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="loopBlock"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="If"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="predicate"
        eType="ecore:EClass ../../com.kaurel.klang.core/model/core.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="ifBlock"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="elseBlock"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ForeverLoop"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="loopStatements"
        upperBound="-1"
        eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Yield"
      eSuperTypes="#//Statement"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableAssignment"
      eSuperTypes="#//Statement">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="scope type&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="expression"
        eType="ecore:EClass ../../com.kaurel.klang.core/model/core.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="variableName"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Or"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="And"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Plus"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Minus"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Multiply"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Divide"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="LessThan"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Equal"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="GreaterThan"
      eSuperTypes="#//BinaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Not"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BooleanLiteral"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DoubleLiteral"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="StringLiteral"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Expression">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="VariableReference"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Expression">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="scope&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="variableName"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UnaryOperator"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Expression">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="type&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="expression"
        eType="ecore:EClass ../../com.kaurel.klang.core/model/core.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="BinaryOperator"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//Expression">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="type&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="left"
        eType="ecore:EClass ../../com.kaurel.klang.core/model/core.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="right"
        eType="ecore:EClass ../../com.kaurel.klang.core/model/core.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="FunctionCall"
      eSuperTypes="#//Statement">
    <eAnnotations
        source="http://www.eclipse.org/emf/2002/Ecore">
      <details
          key="constraints"
          value="methodDeclaration&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parameters"
        upperBound="-1"
        eType="ecore:EClass ../../com.kaurel.klang.core/model/core.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Statement"
      abstract="true"
      interface="true"
      eSuperTypes="#//AbstractElement"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="AbstractElement"
      abstract="true">
    <eOperations
        name="getActor"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="GameStart"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//EventHandler"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="SpriteClicked"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//EventHandler"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="KeyPressed"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="key"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="CollidesWith"
      eSuperTypes="../../com.kaurel.klang.core/model/core.ecore#//EventHandler">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="target"
        eType="#//SpriteActor"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="IntegerLiteral">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="value"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Sleep"
      eSuperTypes="#//Statement">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="duration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="UnaryMinus"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ToDouble"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="ToInt"
      eSuperTypes="#//UnaryOperator"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Program">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="sceneActor"
        eType="#//SceneActor"
        containment="true"
        eOpposite="#//SceneActor/program"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="spriteActors"
        upperBound="-1"
        eType="#//SpriteActor"
        containment="true"
        eOpposite="#//SpriteActor/program"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TreeNode"
      abstract="true"
      interface="true">
    <eTypeParameters
        name="T">
      <eBounds
          eClassifier="#//TreeNode">
        <eTypeArguments
            eTypeParameter="#//TreeNode/T"/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="children"
        upperBound="-1"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"
        resolveProxies="false">
      <eGenericType
          eTypeParameter="#//TreeNode/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="parent"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"
        resolveProxies="false">
      <eGenericType
          eTypeParameter="#//TreeNode/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TreeTraversal">
    <eOperations
        name="BreadthFirst"
        upperBound="-1">
      <eGenericType
          eTypeParameter="#//TreeTraversal/BreadthFirst/T"/>
      <eTypeParameters
          name="T">
        <eBounds
            eClassifier="#//TreeNode">
          <eTypeArguments
              eTypeParameter="#//TreeTraversal/BreadthFirst/T"/>
        </eBounds>
      </eTypeParameters>
      <eParameters
          name="root">
        <eGenericType
            eTypeParameter="#//TreeTraversal/BreadthFirst/T"/>
      </eParameters>
    </eOperations>
    <eOperations
        name="DepthFirst"
        upperBound="-1">
      <eGenericType
          eTypeParameter="#//TreeTraversal/DepthFirst/T"/>
      <eTypeParameters
          name="T">
        <eBounds
            eClassifier="#//TreeNode">
          <eTypeArguments
              eTypeParameter="#//TreeTraversal/DepthFirst/T"/>
        </eBounds>
      </eTypeParameters>
      <eParameters
          name="root">
        <eGenericType
            eTypeParameter="#//TreeTraversal/DepthFirst/T"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
