/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package com.kaurel.klang.xtext.validation;

import com.kaurel.klang.xtext.validation.AbstractKlangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class KlangValidator extends AbstractKlangValidator {
}
